/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

/**
 *
 * @author cbourgouin
 */
public class FenPrinc extends javax.swing.JFrame {

    /**
     * Creates new form FenPrinc
     */
    public FenPrinc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        etiSaisieCode = new javax.swing.JLabel();
        zoneSaisie = new javax.swing.JTextField();
        etiChoixSE = new javax.swing.JLabel();
        comboEntree = new javax.swing.JComboBox<>();
        etiListeSE = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listeOS = new javax.swing.JList<>();
        checkBoxLin = new javax.swing.JCheckBox();
        checkBoxWin = new javax.swing.JCheckBox();
        checkBoxMac = new javax.swing.JCheckBox();
        radioLinux = new javax.swing.JRadioButton();
        radioWindows = new javax.swing.JRadioButton();
        radioMac = new javax.swing.JRadioButton();
        etiMsgEvt = new javax.swing.JLabel();
        changeText = new javax.swing.JLabel();
        mb = new javax.swing.JMenuBar();
        jm1 = new javax.swing.JMenu();
        jm2 = new javax.swing.JMenu();
        im4 = new javax.swing.JMenuItem();
        im5 = new javax.swing.JMenuItem();
        jm3 = new javax.swing.JMenu();
        im1 = new javax.swing.JMenuItem();
        jm4 = new javax.swing.JMenu();
        im2 = new javax.swing.JMenuItem();
        im3 = new javax.swing.JMenuItem();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("exemple d'IHM");
        setBackground(new java.awt.Color(253, 145, 145));
        setMinimumSize(new java.awt.Dimension(250, 350));
        setResizable(false);

        etiSaisieCode.setText("Entrer votre code");

        zoneSaisie.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                zoneSaisieCaretUpdate(evt);
            }
        });
        zoneSaisie.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                zoneSaisieInputMethodTextChanged(evt);
            }
        });
        zoneSaisie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneSaisieActionPerformed(evt);
            }
        });
        zoneSaisie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                zoneSaisieKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zoneSaisieKeyTyped(evt);
            }
        });

        etiChoixSE.setText("choix");

        comboEntree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Linux", "Windows", "Unix", "Solaris" }));
        comboEntree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEntreeActionPerformed(evt);
            }
        });

        etiListeSE.setText("liste");

        listeOS.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Linux", "Windows", "Unix", "Solaris" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listeOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeOSMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listeOS);

        checkBoxLin.setText("Linux");
        checkBoxLin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxLinActionPerformed(evt);
            }
        });

        checkBoxWin.setText("Windows");
        checkBoxWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxWinActionPerformed(evt);
            }
        });

        checkBoxMac.setText("Mac OS");
        checkBoxMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxMacActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioLinux);
        radioLinux.setText("Linux");
        radioLinux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioLinuxMouseClicked(evt);
            }
        });
        radioLinux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLinuxActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioWindows);
        radioWindows.setText("Windows");
        radioWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioWindowsActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioMac);
        radioMac.setText("Mac OS");
        radioMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMacActionPerformed(evt);
            }
        });

        etiMsgEvt.setText("source de l'evenement");

        changeText.setText(" ");

        mb.setBackground(new java.awt.Color(95, 95, 95));

        jm1.setText("Langage");

        jm2.setText("web");

        im4.setText("php");
        im4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im4ActionPerformed(evt);
            }
        });
        jm2.add(im4);

        im5.setText("javascript");
        im5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im5ActionPerformed(evt);
            }
        });
        jm2.add(im5);

        jm1.add(jm2);

        jm3.setText("structuré");

        im1.setText("C");
        im1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im1ActionPerformed(evt);
            }
        });
        jm3.add(im1);

        jm1.add(jm3);

        jm4.setText("objet");

        im2.setText("java");
        im2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im2ActionPerformed(evt);
            }
        });
        jm4.add(im2);

        im3.setText("C++");
        im3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im3ActionPerformed(evt);
            }
        });
        jm4.add(im3);

        jm1.add(jm4);

        mb.add(jm1);

        setJMenuBar(mb);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiSaisieCode)
                            .addComponent(etiChoixSE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zoneSaisie, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiListeSE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeText)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioLinux)
                                .addGap(18, 18, 18)
                                .addComponent(radioWindows)
                                .addGap(18, 18, 18)
                                .addComponent(radioMac))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkBoxLin)
                                .addGap(18, 18, 18)
                                .addComponent(checkBoxWin)
                                .addGap(18, 18, 18)
                                .addComponent(checkBoxMac))
                            .addComponent(etiMsgEvt))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiSaisieCode)
                    .addComponent(zoneSaisie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiChoixSE)
                    .addComponent(comboEntree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(etiListeSE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxLin)
                    .addComponent(checkBoxWin)
                    .addComponent(checkBoxMac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioLinux)
                    .addComponent(radioWindows)
                    .addComponent(radioMac))
                .addGap(18, 18, 18)
                .addComponent(etiMsgEvt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeText))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void im2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im2ActionPerformed
        changeText.setText("dans les languages => java selectionné");
        System.out.println("dans les languages => java selectionné");
    }//GEN-LAST:event_im2ActionPerformed

    private void im3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im3ActionPerformed
        changeText.setText("dans les languages => C++ selectionné");
        System.out.println("dans les languages => C++ selectionné");
    }//GEN-LAST:event_im3ActionPerformed

    private void comboEntreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEntreeActionPerformed
        changeText.setText("dans le combo => "+comboEntree.getItemAt(comboEntree.getSelectedIndex()));
        System.out.println("dans le combo => "+comboEntree.getItemAt(comboEntree.getSelectedIndex()));
    }//GEN-LAST:event_comboEntreeActionPerformed

    private void checkBoxLinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxLinActionPerformed
        if(checkBoxLin.isSelected() == true){
            changeText.setText("dans la case à cocher => Linux coché");
            System.out.println("dans la case à cocher => Linux coché");
        } else {
            changeText.setText("dans la case à cocher => Linux non coché");
            System.out.println("dans la case à cocher => Linux non coché");
        }
    }//GEN-LAST:event_checkBoxLinActionPerformed

    private void checkBoxWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxWinActionPerformed
        if(checkBoxWin.isSelected() == true){
            changeText.setText("dans la case à cocher => Windows coché");
            System.out.println("dans la case à cocher => Windows coché");
        } else {
            changeText.setText("dans la case à cocher => Windows non coché");
            System.out.println("dans la case à cocher => Windows non coché");
        }
    }//GEN-LAST:event_checkBoxWinActionPerformed
        
    private void zoneSaisieInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_zoneSaisieInputMethodTextChanged
        // TODO add your handling code ere:
    }//GEN-LAST:event_zoneSaisieInputMethodTextChanged

    private void radioLinuxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioLinuxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_radioLinuxMouseClicked

    private void zoneSaisieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zoneSaisieKeyPressed

    }//GEN-LAST:event_zoneSaisieKeyPressed

    private void zoneSaisieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zoneSaisieKeyTyped
        if(zoneSaisie.getText().length() >= 4){
            evt.consume();
            changeText.setText("dans la zone de saisie => "+zoneSaisie.getText());
            System.out.println("dans la zone de saisie => "+zoneSaisie.getText());
        }else{
            changeText.setText("dans la zone de saisie => "+zoneSaisie.getText());
            System.out.println("dans la zone de saisie => "+zoneSaisie.getText());
        }
    }//GEN-LAST:event_zoneSaisieKeyTyped

    private void listeOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeOSMouseClicked
        // TODO add your handling code here:
        changeText.setText("dans la liste => "+listeOS.getSelectedValue());
        System.out.println("dans la liste => "+listeOS.getSelectedValue());
    }//GEN-LAST:event_listeOSMouseClicked

    private void zoneSaisieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneSaisieActionPerformed
        
    }//GEN-LAST:event_zoneSaisieActionPerformed

    private void checkBoxMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxMacActionPerformed
        if(checkBoxMac.isSelected() == true){
            changeText.setText("dans la case à cocher => MacOS coché");
            System.out.println("dans la case à cocher => MacOS coché");
        } else {
            changeText.setText("dans la case à cocher => MacOS non coché");
            System.out.println("dans la case à cocher => MacOS non coché");
        }
    }//GEN-LAST:event_checkBoxMacActionPerformed

    private void radioLinuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLinuxActionPerformed
        changeText.setText("dans le radio bouton => Linux coché");
        System.out.println("dans le radio bouton => Linux coché");
    }//GEN-LAST:event_radioLinuxActionPerformed

    private void radioWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioWindowsActionPerformed
        changeText.setText("dans le radio bouton => Windows coché");
        System.out.println("dans le radio bouton => Windows coché");
    }//GEN-LAST:event_radioWindowsActionPerformed

    private void radioMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMacActionPerformed
        changeText.setText("dans le radio bouton => MacOS coché");
        System.out.println("dans le radio bouton => MacOS coché");
    }//GEN-LAST:event_radioMacActionPerformed

    private void zoneSaisieCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_zoneSaisieCaretUpdate

    }//GEN-LAST:event_zoneSaisieCaretUpdate

    private void im4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im4ActionPerformed
        changeText.setText("dans les languages => php selectionné");
        System.out.println("dans les languages => php selectionné");
    }//GEN-LAST:event_im4ActionPerformed

    private void im5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im5ActionPerformed
        changeText.setText("dans les languages => javascript selectionné");
        System.out.println("dans les languages => javascript selectionné");
    }//GEN-LAST:event_im5ActionPerformed

    private void im1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im1ActionPerformed
        changeText.setText("dans les languages => C selectionné");
        System.out.println("dans les languages => C selectionné");
    }//GEN-LAST:event_im1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenPrinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenPrinc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel changeText;
    private javax.swing.JCheckBox checkBoxLin;
    private javax.swing.JCheckBox checkBoxMac;
    private javax.swing.JCheckBox checkBoxWin;
    private javax.swing.JComboBox<String> comboEntree;
    private javax.swing.JLabel etiChoixSE;
    private javax.swing.JLabel etiListeSE;
    private javax.swing.JLabel etiMsgEvt;
    private javax.swing.JLabel etiSaisieCode;
    private javax.swing.JMenuItem im1;
    private javax.swing.JMenuItem im2;
    private javax.swing.JMenuItem im3;
    private javax.swing.JMenuItem im4;
    private javax.swing.JMenuItem im5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu jm1;
    private javax.swing.JMenu jm2;
    private javax.swing.JMenu jm3;
    private javax.swing.JMenu jm4;
    private javax.swing.JList<String> listeOS;
    private javax.swing.JMenuBar mb;
    private javax.swing.JRadioButton radioLinux;
    private javax.swing.JRadioButton radioMac;
    private javax.swing.JRadioButton radioWindows;
    private javax.swing.JTextField zoneSaisie;
    // End of variables declaration//GEN-END:variables
}
